default_args:
  owner: DataOps Team
  depends_on_past: False
  start_date: 2022-05-13T00:00:00
  email_on_failure: False
  email_on_retry: False
  retries: 0
  retry_delay: 5m

dag:
  dag_id: simple_project
  description: 'Simple transforming'
  schedule_interval: '0 12 * * *'
  catchup: False
  max_active_runs: 1
  concurrency: 2

dags_path: "gs://europe-central2-dataops-com-0cce19dc-bucket/dags/simple_project"

manifest_file_name: manifest.json
seed_task: False
use_task_group: True

#failure_handlers:
#  - type: slack
#    connection_id: slack_failure
#    message_template: |
#        :red_circle: Task Failed.
#        *Task*: {task}
#        *Dag*: {dag}
#        *Execution Time*: {execution_time}
#        *Log Url*: {url}