source:
  type: "dbt"
  config:
    manifest_path: "./target/manifest.json"
    catalog_path: "./target/catalog.json"
    sources_path: "./target/sources.json"

    target_platform: "bigquery"
    disable_dbt_node_creation: True
    load_schemas: True
    env: "DEV"

    # node_type_pattern is checking `nodes/{{node_name}}/resource_type`
    # field in dbt's `manifest.json`;
    # known types: [model, test, source, macro]
    node_type_pattern:
      deny:
        - ^test.*
      allow:
        - ^.*

transformers:
  - type: "simple_add_dataset_tags"
    config:
      tag_urns:
        - "urn:li:tag:simple_project"
  - type: "simple_add_dataset_ownership"
    config:
      owner_urns:
        - "urn:li:corpuser:DataOps Team"
      ownership_type: "PRODUCER"
  - type: "set_dataset_browse_path"
    config:
      replace_existing: True
      path_templates:
        - /DATASET_PARTS

sink:
  type: "datahub-rest"
  config:
    server: "http://34.118.20.215:8080"
