image_pull_policy: IfNotPresent
namespace: default

secrets:
  - secret: service-account
    deploy_type: volume
    deploy_target: /var
    key: gc-key.json

envs:
  GCP_KEY_PATH: "/var/gc-key.json"

labels:
  runner: airflow

is_delete_operator_pod: True

resources:
  limit:
    memory: 1024M
    cpu: 100m
  requests:
    memory: 1024M
    cpu: 100m