services:
  - name: docker:19.03.13-dind

include:
  - https://raw.githubusercontent.com/getindata/gitlab_cicd_templates/v0.0.1/dataops/gcp/gcp_setup_template.yml
  - https://raw.githubusercontent.com/getindata/gitlab_cicd_templates/v0.0.1/dataops/dev_cicd_template.yml

variables:
  GS_BUCKET: $GS_BUCKET
  DOCKER_REGISTRY: europe-central2-docker.pkg.dev
  GITLAB_CICD_IMAGE_REPO: gcr.io/getindata-images-public/cicd-dataops
  GITLAB_CICD_IMAGE_TAG: gcp-0.1.1
  BLOB_CONFIG_PATH: blob_args.json

stages:
  - execute-dev

